"use client"
import React , { useState } from 'react';
import { setCookies } from 'cookies-next';
import Service from './../api/Service';
import logo from './../logo.png';
import Head from 'next/head'
import Image from 'next/image'
import styles from './../page.module.css'
import Swal from 'sweetalert2';

export default function Home() {
  const [NewPass, setNewPass] = useState('');
  const [ConfirmPass, setConfirmPass] = useState('');
  const [Message, setMessage] = useState('');
  const [MessageL, setMessageL] = useState('');
  const [disabled, setDisabled] = useState(true);

  const inputNewPass =(event)=>{
    setNewPass(event.target.value);
  }
  const inputConfirmPass =(event)=>{
    setConfirmPass(event.target.value);
  }
  const CheckPassword =(event)=>{

    if(ConfirmPass!=NewPass) {
        setMessage("Password don't match.");
    } else {
        setMessage('');
    }

    checkDisabled();

  }
  const CheckLength =(event)=>{

    if(NewPass.length<8) {
        setMessageL("Password 8-12 characters.");
    } else {
        setMessageL('');

    }

    checkDisabled();

  }

  const checkDisabled =()=>{

    if(NewPass.length<8 || ConfirmPass!=NewPass) {
        setDisabled(true);
    } else {
        setDisabled(false);

    }

  }


  const submiPasswoed = (event) => {
    let Password = NewPass;
      if (Password) {
        new Service().resetPassword(getCookie('token'),Password).then(res => {
            // console.log(JSON.stringify(res.data));
          if (res.data.status === '1') {
            setCookies('token', res.data.token, { path: '/', domain: '', maxAge: 4 * 60 * 60 });
            window.location.href='/home';
          }
        });
      } 
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Timesheet - Backend</title>
        <meta name="description" content="Generated by Unique" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className={styles.main}>
        <div className="row">
          <div className="col-12">     
            <div className="login-card">
              <div>
                  <div className="text-center mb-3">
                      <a >
                          <Image  src={logo} alt="looginpage" width={100} />
                      </a>
                  </div>
                  <div className="login-main"> 
                      <form className="theme-form" onSubmit={submiPasswoed}>
                          <h4>Reset Your Password</h4>
                          <div className="form-group">
                              <label className="col-form-label">New Password</label>
                              <input className="form-control" type="password" min={8}  onChange={inputNewPass} onBlur={CheckLength} />
                              <label className="text-danger f-12 mt-1">{MessageL}</label>
                          </div>
                          <div className="form-group">
                              <label className="col-form-label">Confirm Password</label>
                              <input className="form-control" type="password" min={8}  onChange={inputConfirmPass} onBlur={CheckPassword} />
                              <label className="text-danger f-12 mt-1">{Message}</label>
                          </div>
                          <div className="form-group mb-0 mt-4 text-center">
                              <button className="btn btn-sm btn-primary" type="submit" disabled={disabled} >Save Password</button>
                          </div>
                      </form>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  )
}
